name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main_YH.py

      - name: Commit and push files
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Update files and logs"
          git push
