name: Create Release

on:
  workflow_dispatch:  # 新增的手动触发事件
    inputs:
      version:       # 自定义输入项，用于手动指定版本号（可选）
        description: 'Manual version input (optional)'
        required: false
        default: 'manual-release'  # 默认版本号，若未手动输入

  push:
    tags:
      - '版本-*'  # 匹配以"版本-"开头的标签，自动化触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag name or manual input
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            echo ::set-output name=VERSION::${{ github.event.inputs.version }}
          else
            TAG_NAME=${GITHUB_REF#refs/tags/}
            VERSION=$(echo "$TAG_NAME" | cut -d'-' -f2)
            echo ::set-output name=VERSION::$VERSION
          fi
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}  # 使用手动输入或标签名
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      # 注意：若上传资源路径依赖于版本号，请确保它正确无误
      # - name: Upload Release Asset
      #   ...（省略具体配置，以保持示例简洁）

      # 注意：若上传资源，请取消上述步骤的注释，并根据需要调整asset_path等参数
