name: Upload NetworkSetup.exe Release

on:
  push:
    tags:
      - '版本-*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#版本-}
          echo ::set-output name=VERSION::$VERSION
        shell: bash

      - name: Find NetworkSetup.exe in versioned folder
        id: find_networksetup
        run: |
          FOLDER_PATH="./版本-${{ steps.extract_version.outputs.VERSION }}"
          if [ -d "$FOLDER_PATH" ]; then
            FILE_PATH="$FOLDER_PATH/羽华SMT快速编程系统NetworkSetup.exe"
            if [ -f "$FILE_PATH" ]; then
              echo ::set-output name=FILE_PATH::$FILE_PATH
            else
              echo "NetworkSetup.exe not found in folder $FOLDER_PATH"
              exit 1
            fi
          else
            echo "Folder $FOLDER_PATH not found"
            exit 1
          fi
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release NetworkSetup ${{ steps.extract_version.outputs.VERSION }}
          body: |
            This release includes NetworkSetup.exe for version ${{ steps.extract_version.outputs.VERSION }}.
          draft: false
          prerelease: false

      - name: Upload NetworkSetup.exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_networksetup.outputs.FILE_PATH }}
          asset_name: NetworkSetup-${{ steps.extract_version.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream
